version: '1.29.0'

services:
 postgres:
 container_name: camilo_postgres
 image: postgres

 ports: -5432:5432
 enviroment:
 - POSTGRES_USER=admin
 - POSTGRES_PASSWORD=admin
 - postgres_db=camilo
 
